# https://docs.coderabbit.ai/reference/configuration#reference
reviews:
  high_level_summary: true
  high_level_summary_in_walkthrough: true
  high_level_summary_placeholder: '@coderabbitai summary'
  auto_title_placeholder: '@coderabbitai'
