{
 "title": "Overview of motowear.gr",
 "tags": [
  "nextjs",
  "nodejs"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Uptime",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "up{job=\"nextjs\"}"
    }
   ]
  },
  {
   "title": "Postgres Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "nextjs_postgres_connections" }
   ]
  },
  {
   "title": "Redis Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "nextjs_redis_memory_bytes" }
   ]
  }
 ]
}